/*
    CONSTANTES PARA EL CRUD DE LAS UNITS
  */

export const ELICAL_LIST_REQUEST = "ELICAL_LIST_REQUEST";
export const ELICAL_LIST_SUCCESS = "ELICAL_LIST_SUCCESS";
export const ELICAL_LIST_FAIL = "ELICAL_LIST_FAIL";

export const ELICAL_LIST_RESET = "ELICAL_LIST_RESET";

export const ELICAL_DETAILS_REQUEST = "ELICAL_DETAILS_REQUEST";
export const ELICAL_DETAILS_SUCCESS = "ELICAL_DETAILS_SUCCESS";
export const ELICAL_DETAILS_FAIL = "ELICAL_DETAILS_FAIL";

export const ELICAL_DELETE_REQUEST = "ELICAL_DELETE_REQUEST";
export const ELICAL_DELETE_SUCCESS = "ELICAL_DELETE_SUCCESS";
export const ELICAL_DELETE_FAIL = "ELICAL_DELETE_FAIL";

export const ELICAL_CREATE_REQUEST = "ELICAL_CREATE_REQUEST";
export const ELICAL_CREATE_SUCCESS = "ELICAL_CREATE_SUCCESS";
export const ELICAL_CREATE_FAIL = "ELICAL_CREATE_FAIL";

export const ELICAL_UPDATE_REQUEST = "ELICAL_UPDATE_REQUEST";
export const ELICAL_UPDATE_SUCCESS = "ELICAL_UPDATE_SUCCESS";
export const ELICAL_UPDATE_FAIL = "ELICAL_UPDATE_FAIL";
export const ELICAL_UPDATE_RESET = "ELICAL_UPDATE_RESET";
