/*
    CONSTANTES PARA EL CRUD DE LAS UNITS
  */

export const ELITROL_LIST_REQUEST = "ELITROL_LIST_REQUEST";
export const ELITROL_LIST_SUCCESS = "ELITROL_LIST_SUCCESS";
export const ELITROL_LIST_FAIL = "ELITROL_LIST_FAIL";

export const ELITROL_LIST_RESET = "ELITROL_LIST_RESET";

export const ELITROL_DETAILS_REQUEST = "ELITROL_DETAILS_REQUEST";
export const ELITROL_DETAILS_SUCCESS = "ELITROL_DETAILS_SUCCESS";
export const ELITROL_DETAILS_FAIL = "ELITROL_DETAILS_FAIL";

export const ELITROL_DELETE_REQUEST = "ELITROL_DELETE_REQUEST";
export const ELITROL_DELETE_SUCCESS = "ELITROL_DELETE_SUCCESS";
export const ELITROL_DELETE_FAIL = "ELITROL_DELETE_FAIL";

export const ELITROL_CREATE_REQUEST = "ELITROL_CREATE_REQUEST";
export const ELITROL_CREATE_SUCCESS = "ELITROL_CREATE_SUCCESS";
export const ELITROL_CREATE_FAIL = "ELITROL_CREATE_FAIL";

export const ELITROL_UPDATE_REQUEST = "ELITROL_UPDATE_REQUEST";
export const ELITROL_UPDATE_SUCCESS = "ELITROL_UPDATE_SUCCESS";
export const ELITROL_UPDATE_FAIL = "ELITROL_UPDATE_FAIL";
export const ELITROL_UPDATE_RESET = "ELITROL_UPDATE_RESET";
