/*
    CONSTANTES PARA EL CRUD DE LOS FOLLETO
  */

export const FOLLETOS_LIST_REQUEST = " FOLLETOS_LIST_REQUEST";
export const FOLLETOS_LIST_SUCCESS = " FOLLETOS_LIST_SUCCESS";
export const FOLLETOS_LIST_FAIL = " FOLLETOS_LIST_FAIL";

export const FOLLETOS_LIST_RESET = " FOLLETOS_LIST_RESET";

export const FOLLETOS_DETAILS_REQUEST = " FOLLETOS_DETAILS_REQUEST";
export const FOLLETOS_DETAILS_SUCCESS = " FOLLETOS_DETAILS_SUCCESS";
export const FOLLETOS_DETAILS_FAIL = " FOLLETOS_DETAILS_FAIL";

export const FOLLETOS_DELETE_REQUEST = " FOLLETOS_DELETE_REQUEST";
export const FOLLETOS_DELETE_SUCCESS = " FOLLETOS_DELETE_SUCCESS";
export const FOLLETOS_DELETE_FAIL = " FOLLETOS_DELETE_FAIL";

export const FOLLETOS_CREATE_REQUEST = " FOLLETOS_CREATE_REQUEST";
export const FOLLETOS_CREATE_SUCCESS = " FOLLETOS_CREATE_SUCCESS";
export const FOLLETOS_CREATE_FAIL = " FOLLETOS_CREATE_FAIL";

export const FOLLETOS_UPDATE_REQUEST = " FOLLETOS_UPDATE_REQUEST";
export const FOLLETOS_UPDATE_SUCCESS = " FOLLETOS_UPDATE_SUCCESS";
export const FOLLETOS_UPDATE_FAIL = " FOLLETOS_UPDATE_FAIL";
export const FOLLETOS_UPDATE_RESET = " FOLLETOS_UPDATE_RESET";
