/*
    CONSTANTES PARA EL CRUD DE LAS UNITS
  */

export const METHODES_LIST_REQUEST = "METHODES_LIST_REQUEST";
export const METHODES_LIST_SUCCESS = "METHODES_LIST_SUCCESS";
export const METHODES_LIST_FAIL = "METHODES_LIST_FAIL";

export const METHODES_LIST_RESET = "METHODES_LIST_RESET";

export const METHODES_DETAILS_REQUEST = "METHODES_DETAILS_REQUEST";
export const METHODES_DETAILS_SUCCESS = "METHODES_DETAILS_SUCCESS";
export const METHODES_DETAILS_FAIL = "METHODES_DETAILS_FAIL";

export const METHODES_DELETE_REQUEST = "METHODES_DELETE_REQUEST";
export const METHODES_DELETE_SUCCESS = "METHODES_DELETE_SUCCESS";
export const METHODES_DELETE_FAIL = "METHODES_DELETE_FAIL";

export const METHODES_CREATE_REQUEST = "METHODES_CREATE_REQUEST";
export const METHODES_CREATE_SUCCESS = "METHODES_CREATE_SUCCESS";
export const METHODES_CREATE_FAIL = "METHODES_CREATE_FAIL";

export const METHODES_UPDATE_REQUEST = "METHODES_UPDATE_REQUEST";
export const METHODES_UPDATE_SUCCESS = "METHODES_UPDATE_SUCCESS";
export const METHODES_UPDATE_FAIL = "METHODES_UPDATE_FAIL";
export const METHODES_UPDATE_RESET = "METHODES_UPDATE_RESET";
