/*
    CONSTANTES PARA EL CRUD DE LAS QUIMICAS
  */

export const QUIMICAS_LIST_REQUEST = " QUIMICAS_LIST_REQUEST";
export const QUIMICAS_LIST_SUCCESS = " QUIMICAS_LIST_SUCCESS";
export const QUIMICAS_LIST_FAIL = " QUIMICAS_LIST_FAIL";

export const QUIMICAS_LIST_RESET = " QUIMICAS_LIST_RESET";

export const QUIMICAS_DETAILS_REQUEST = " QUIMICAS_DETAILS_REQUEST";
export const QUIMICAS_DETAILS_SUCCESS = " QUIMICAS_DETAILS_SUCCESS";
export const QUIMICAS_DETAILS_FAIL = " QUIMICAS_DETAILS_FAIL";

export const QUIMICAS_DELETE_REQUEST = " QUIMICAS_DELETE_REQUEST";
export const QUIMICAS_DELETE_SUCCESS = " QUIMICAS_DELETE_SUCCESS";
export const QUIMICAS_DELETE_FAIL = " QUIMICAS_DELETE_FAIL";

export const QUIMICAS_CREATE_REQUEST = " QUIMICAS_CREATE_REQUEST";
export const QUIMICAS_CREATE_SUCCESS = " QUIMICAS_CREATE_SUCCESS";
export const QUIMICAS_CREATE_FAIL = " QUIMICAS_CREATE_FAIL";

export const QUIMICAS_UPDATE_REQUEST = " QUIMICAS_UPDATE_REQUEST";
export const QUIMICAS_UPDATE_SUCCESS = " QUIMICAS_UPDATE_SUCCESS";
export const QUIMICAS_UPDATE_FAIL = " QUIMICAS_UPDATE_FAIL";
export const QUIMICAS_UPDATE_RESET = " QUIMICAS_UPDATE_RESET";
