/*
    CONSTANTES PARA EL CRUD DE LAS UNITS
  */

export const TRACEABILITY_LIST_REQUEST = "TRACEABILITY_LIST_REQUEST";
export const TRACEABILITY_LIST_SUCCESS = "TRACEABILITY_LIST_SUCCESS";
export const TRACEABILITY_LIST_FAIL = "TRACEABILITY_LIST_FAIL";

export const TRACEABILITY_LIST_RESET = "TRACEABILITY_LIST_RESET";

export const TRACEABILITY_DETAILS_REQUEST = "TRACEABILITY_DETAILS_REQUEST";
export const TRACEABILITY_DETAILS_SUCCESS = "TRACEABILITY_DETAILS_SUCCESS";
export const TRACEABILITY_DETAILS_FAIL = "TRACEABILITY_DETAILS_FAIL";

export const TRACEABILITY_DELETE_REQUEST = "TRACEABILITY_DELETE_REQUEST";
export const TRACEABILITY_DELETE_SUCCESS = "TRACEABILITY_DELETE_SUCCESS";
export const TRACEABILITY_DELETE_FAIL = "TRACEABILITY_DELETE_FAIL";

export const TRACEABILITY_CREATE_REQUEST = "TRACEABILITY_CREATE_REQUEST";
export const TRACEABILITY_CREATE_SUCCESS = "TRACEABILITY_CREATE_SUCCESS";
export const TRACEABILITY_CREATE_FAIL = "TRACEABILITY_CREATE_FAIL";

export const TRACEABILITY_UPDATE_REQUEST = "TRACEABILITY_UPDATE_REQUEST";
export const TRACEABILITY_UPDATE_SUCCESS = "TRACEABILITY_UPDATE_SUCCESS";
export const TRACEABILITY_UPDATE_FAIL = "TRACEABILITY_UPDATE_FAIL";
export const TRACEABILITY_UPDATE_RESET = "TRACEABILITY_UPDATE_RESET";
