/*
    CONSTANTES PARA EL CRUD DE LAS UNITS
  */

export const UNITS_LIST_REQUEST = "UNITS_LIST_REQUEST";
export const UNITS_LIST_SUCCESS = "UNITS_LIST_SUCCESS";
export const UNITS_LIST_FAIL = "UNITS_LIST_FAIL";

export const UNITS_LIST_RESET = "UNITS_LIST_RESET";

export const UNITS_DETAILS_REQUEST = "UNITS_DETAILS_REQUEST";
export const UNITS_DETAILS_SUCCESS = "UNITS_DETAILS_SUCCESS";
export const UNITS_DETAILS_FAIL = "UNITS_DETAILS_FAIL";

export const UNITS_DELETE_REQUEST = "UNITS_DELETE_REQUEST";
export const UNITS_DELETE_SUCCESS = "UNITS_DELETE_SUCCESS";
export const UNITS_DELETE_FAIL = "UNITS_DELETE_FAIL";

export const UNITS_CREATE_REQUEST = "UNITS_CREATE_REQUEST";
export const UNITS_CREATE_SUCCESS = "UNITS_CREATE_SUCCESS";
export const UNITS_CREATE_FAIL = "UNITS_CREATE_FAIL";

export const UNITS_UPDATE_REQUEST = "UNITS_UPDATE_REQUEST";
export const UNITS_UPDATE_SUCCESS = "UNITS_UPDATE_SUCCESS";
export const UNITS_UPDATE_FAIL = "UNITS_UPDATE_FAIL";
export const UNITS_UPDATE_RESET = "UNITS_UPDATE_RESET";
