# Generated by Django 4.0.6 on 2023-02-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lote', models.CharField(max_length=10, null=True, verbose_name='Lote')),
                ('fecha', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Methodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nombre_quimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_quimica', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traceability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceability', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfoFolletoElitrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankmiddle', models.FloatField()),
                ('ranklow', models.FloatField()),
                ('rankhigh', models.FloatField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folletos.nombre_quimica')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folletos.methodes')),
                ('propidedades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propidedades', to='folletos.units')),
            ],
        ),
        migrations.CreateModel(
            name='InfoFolletoElical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=25)),
                ('value', models.FloatField()),
                ('valor', models.FloatField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folletos.methodes')),
                ('propiedadSg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedadsg', to='folletos.units')),
                ('pvalor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pvalors', to='folletos.units')),
                ('quimica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folletos.nombre_quimica')),
                ('traceability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folletos.traceability')),
            ],
        ),
    ]
